#!/bin/sh
# A simple Todo List using notify-send

#image='$HOME/Pictures/notify/todo/bg.png'

. $HOME/.local/bin/color-parser

notify-send "
<span foreground='$FG'>
<span foreground='$BRED' >    TODO Weekdays </span> 
<span foreground='$WHITE' >    -=-=-=-=-=-=-</span> 

<span foreground='$RED'>1. </span>MIT Sec Videos   <span foreground='$FG'></span>
<span foreground='$RED'>2. </span>HackArtExploit   <span foreground='$FG'></span>
<span foreground='$RED'>3. </span>Metasploitable   <span foreground='$FG'></span>
<span foreground='$RED'>4. </span>Hacker Playbook  <span foreground='$FG'></span>
<span foreground='$RED'>5. </span>WebApp Hack      <span foreground='$FG'></span>

<span foreground='$BRED' >    TODO Weekend </span> 
<span foreground='$WHITE' >    -=-=-=-=-=-=-</span> 

<span foreground='$RED'>1. </span>Google Hack      <span foreground='$FG'></span>
<span foreground='$RED'>2. </span>TheShellcoders   <span foreground='$FG'></span>
<span foreground='$RED'>3. </span>Counter Hack     <span foreground='$FG'></span>
<span foreground='$RED'>4. </span>Practical vim    <span foreground='$FG'></span>
<span foreground='$RED'>5. </span>GNS3             <span foreground='$FG'></span>
</span>
"
