#!/bin/bash
# Description: Display cover for the current playing song using notify-send

# source colors
. $HOME/.local/bin/color-parser

# create notify title
title="<span foreground='$MAGENTA'>Now Playing</span>"

# get current album
album=$(ncmpcpp --current-song={%b} 2> /dev/null)

# If album not null display cover
if [[ -n "$album" ]];then
        if [[ "$album" = "Quran" ]];then
                image="/home/cOb4l7/Pictures/notify/quran/cover.jpg"
                notify-send -i $image "$title" "$(mpc current)"
        elif [[ "$album" = "Quran — Shatri" ]] || [[ "$album" = "Quran" ]] || [[ "$album" = "Mishary Alafasi Musshaf" ]];then
                image="/home/cOb4l7/Pictures/notify/quran/cover.jpg"
                notify-send -i $image "$title" "$(mpc current)"
        else
                image="/home/cOb4l7/Pictures/notify/other/cover.jpg"
                notify-send -i $image "$title" "$(mpc current)"
        fi
else
        image="/home/cOb4l7/Pictures/notify/other/cover.jpg"
        notify-send -i $image "$title" "$(mpc current)"
fi
