#!/usr/bin/bash
seconds="$(< /proc/uptime)"
seconds="${seconds/.*}"

days="$((seconds / 60 / 60 / 24))"
hours="$((seconds / 60 / 60 % 24))"
mins="$((seconds / 60 % 60)) min"


if [[ "$days" != "0" ]];then
        uptime="days: $days, $hours, $mins"
        echo "$uptime"
elif [[ "$hours" = "0" ]];then
        uptime="$mins"
        echo "$uptime"
else
        uptime="$hours hrs, $mins"
        echo "$uptime"
fi
