#! /bin/sh
#                                                                      
#  ▄▄                                                                   
#  ██                                                                   
#  ██▄███▄   ▄▄█████▄  ██▄███▄  ██      ██ ████▄██▄   ██▄████   ▄█████▄ 
#  ██▀  ▀██  ██▄▄▄▄ ▀  ██▀  ▀██ ▀█  ██  █▀ ██ ██ ██   ██▀      ██▀    ▀ 
#  ██    ██   ▀▀▀▀██▄  ██    ██  ██▄██▄██  ██ ██ ██   ██       ██       
#  ███▄▄██▀  █▄▄▄▄▄██  ███▄▄██▀  ▀██  ██▀  ██ ██ ██   ██       ▀██▄▄▄▄█ 
#  ▀▀ ▀▀▀     ▀▀▀▀▀▀   ██ ▀▀▀     ▀▀  ▀▀   ▀▀ ▀▀ ▀▀   ▀▀         ▀▀▀▀▀  
#                      ██                                               
#    
#                                     Config by: https://github.com/cOb4l7
#

#
#  Autostart Commands
#

. $HOME/.local/bin/color-parser
#. $HOME/.local/bin/barstart &
BLK="#151515"
#
# Monitor & Destop Settings
# 

bspc monitor -d surf code docs medi rscn term labs apps expl misc


#
# Global Settings
#

bspc config normal_border_color   "$BLK"
bspc config focused_border_color  "$BLK"
bspc config urgent_border_color   "$BLK"
bspc config presel_border_color   "$BLK"

bspc config window_gap            0
bspc config border_width          2

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true


#
#  Rule Settings
#

bspc rule -a Firefox desktop='^1' follow=on
bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a Zathura desktop='^3' state=tiled follow=on
bspc rule -a mpv desktop='^4' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Wireshark desktop='^8' follow=on
bspc rule -a Nitrogen state=floating focus=on
bspc rule -a feh state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
