#! /bin/sh
#                                                                      
#  ▄▄                                                                   
#  ██                                                                   
#  ██▄███▄   ▄▄█████▄  ██▄███▄  ██      ██ ████▄██▄   ██▄████   ▄█████▄ 
#  ██▀  ▀██  ██▄▄▄▄ ▀  ██▀  ▀██ ▀█  ██  █▀ ██ ██ ██   ██▀      ██▀    ▀ 
#  ██    ██   ▀▀▀▀██▄  ██    ██  ██▄██▄██  ██ ██ ██   ██       ██       
#  ███▄▄██▀  █▄▄▄▄▄██  ███▄▄██▀  ▀██  ██▀  ██ ██ ██   ██       ▀██▄▄▄▄█ 
#  ▀▀ ▀▀▀     ▀▀▀▀▀▀   ██ ▀▀▀     ▀▀  ▀▀   ▀▀ ▀▀ ▀▀   ▀▀         ▀▀▀▀▀  
#                      ██                                               
#    
#                                     Config by: https://github.com/cOb4l7
#

#
#  Autostart Commands
#

. $HOME/.local/bin/color-parser

# Check if the monitor is connected
if `xrandr -q | grep -q "HDMI2 connected"`
then
        BLK="#0b0d16"
        BL="#101010"
        #
        # Monitor & Destop Settings
        # 

        bspc monitor eDP1 -d 1 2 3 4
        bspc monitor HDMI2 -d 5 6 7 8 9 0
        bspc config -m HDMI2 window_gap           10
        bspc config -m HDMI2 border_width         5
        bspc config -m eDP1 window_gap            0
        bspc config -m eDP1 border_width          1

        #
        # Global Settings
        #

        bspc config -m HDMI2 normal_border_color   "$BLK"
        bspc config -m eDP1 normal_border_color    "$BL"
        bspc config -m HDMI2 focused_border_color  "$BLK"
        bspc config -m eDP1 focused_border_color   "$BL"
        bspc config -m HDMI2 urgent_border_color   "$BLK"
        bspc config -m eDP1 urgent_border_color    "$BL"
        bspc config -m HDMI2 presel_border_color   "$BLK"
        bspc config -m eDP1 presel_border_color    "$BL"

        #
        # Start compton
        #
        compton --config ~/.compton.conf -b 
else
        BLK="#101010"
        #
        # Monitor & Destop Settings
        # 

        bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
        bspc config window_gap            0
        bspc config border_width          1

        #
        # Global Settings
        #

        bspc config normal_border_color   "$BLK"
        bspc config focused_border_color  "$BLK"
        bspc config urgent_border_color   "$BLK"
        bspc config presel_border_color   "$BLK"
fi


#
# Global Settings
#

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true


#
#  Rule Settings
#

bspc rule -a Firefox desktop='^5' follow=on
bspc rule -a Chromium desktop='^5' follow=on
bspc rule -a Zathura desktop='^6' state=tiled follow=on
bspc rule -a mpv desktop='^6' follow=on
bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Wireshark desktop='^8' follow=on
bspc rule -a Pcmanfm desktop='^8' follow=on
bspc rule -a Nitrogen state=floating focus=on
bspc rule -a feh state=floating focus=on
bspc rule -a Lxappearance state=floating focus=on
