[admiral]
items = [
         "right", "pow",
         "center", "mail", "ram", "temp", "net", "clock",  "battery",
         "left", "menu"
        ]

[workspaces]
path = "python $HOME/.config/admiral.d/workspace"

# [title]
# path = "xtitle -s -t 40"

[mail]
path = ". $HOME/.config/admiral.d/mail"
reload = 30

[packages]
path = ". $HOME/.config/admiral.d/packages"
reload = 80

[updates]
path = ". $HOME/.config/admiral.d/updates"
reload = 120

[uptime]
path = ". $HOME/.config/admiral.d/uptime"
reload = 1

[kernel]
path = ". $HOME/.config/admiral.d/kernel"
static = true

[volume]
path = ". $HOME/.config/admiral.d/vol"
reload = 0.1

[ram]
path = ". $HOME/.config/admiral.d/ram"
reload = 0.5

[net]
path = ". $HOME/.config/admiral.d/net"
reload = 20

[battery]
path = ". $HOME/.config/admiral.d/battery"
reload = 10

[clock]
path = ". $HOME/.config/admiral.d/clock"
reload = 1

[temp]
path = ". $HOME/.config/admiral.d/temp"
reload = 0.5

[music]
path = ". $HOME/.config/admiral.d/music"


# Clickable areas
[pow]
path = 'echo "%{A:. $HOME/.config/admiral.d/popups/power/power:}%{B#6c71c4}%{F#fdf6e3}    %{A}%{B-}"'
static = true

[menu]
path = 'echo "%{A:. $HOME/.config/admiral.d/popups/todo/todo:}%{B#268bd2}%{F#fdf6e3}    %{A}%{B-}"'
static = true

# [music_control]
# path = 'echo "%{F#928374}%{A:mpc prev &> /dev/null:}%{A}%{A:mpc play &> /dev/null:}%{A}%{A:mpc pause &> /dev/null:}%{A}%{A:mpc next &> /dev/null:}%{A} "'
# static=true

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
